// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9gixdN1FkW4HPcwKtSwO2v2pjQAJHI5M',
    appId: '1:912944915034:web:4298ee726ccbf43396ee63',
    messagingSenderId: '912944915034',
    projectId: 'chat-flutter-b2743',
    authDomain: 'chat-flutter-b2743.firebaseapp.com',
    databaseURL: 'https://chat-flutter-b2743-default-rtdb.firebaseio.com',
    storageBucket: 'chat-flutter-b2743.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3uKlE6qd9fkCnPkWz3vnu_V5Gq1tM_SY',
    appId: '1:912944915034:android:1e9ebaaa13432b6896ee63',
    messagingSenderId: '912944915034',
    projectId: 'chat-flutter-b2743',
    databaseURL: 'https://chat-flutter-b2743-default-rtdb.firebaseio.com',
    storageBucket: 'chat-flutter-b2743.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8eCAHZu1SCQYjXpaEsRXat7mWxQzHXuQ',
    appId: '1:912944915034:ios:2411bec99eef2d0096ee63',
    messagingSenderId: '912944915034',
    projectId: 'chat-flutter-b2743',
    databaseURL: 'https://chat-flutter-b2743-default-rtdb.firebaseio.com',
    storageBucket: 'chat-flutter-b2743.appspot.com',
    androidClientId: '912944915034-lghav8l3mcl280srlu1iftq6b4m5arta.apps.googleusercontent.com',
    iosClientId: '912944915034-1ouvbrth07f50lca3jqa7ov6ldd8d7ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatOnlineFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8eCAHZu1SCQYjXpaEsRXat7mWxQzHXuQ',
    appId: '1:912944915034:ios:2411bec99eef2d0096ee63',
    messagingSenderId: '912944915034',
    projectId: 'chat-flutter-b2743',
    databaseURL: 'https://chat-flutter-b2743-default-rtdb.firebaseio.com',
    storageBucket: 'chat-flutter-b2743.appspot.com',
    androidClientId: '912944915034-lghav8l3mcl280srlu1iftq6b4m5arta.apps.googleusercontent.com',
    iosClientId: '912944915034-1ouvbrth07f50lca3jqa7ov6ldd8d7ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatOnlineFlutter',
  );
}
